### ISSUE TITLE
Зачем вам XML?

### ISSUE THREAD

**Issue by vladcto** [rad55RUS/ProjectSugarUnicorn#7]
Обычный текстовик в формате ```.CSV```, парсится также легко, как я отлетаю на допсу 😢 

**.csv**
```
1;2
2;4
3;8
4;16
```
Затем парсишь как:
```cs
var data = csv.Split('\n').ToList()
                .Select((e) => e.Split(';')
                    .Select((num) => float.Parse(num)).ToList())
                .ToList();
```

И получаешь для примера:
```py
[
    [1, 2]
    [2, 4]
    [3, 8]
    [4, 16]
]
```

**Comment by rad55RUS** [comment]
Если работаешь в VS, то с использованием разметки парсить гораздо удобнее, особенно при большом кол-ве входных данных + достигается хорошая тестируемость

**Comment by vladcto** [comment]
> Если работаешь в VS, то с использованием разметки парсить гораздо удобнее, особенно при большом кол-ве входных данных + достигается хорошая тестируемость

Про удобство в VS согласен, но парсить легче когда у тебя количество данных будет явно больше 4-5, они будут неоднородны и могут иметь разные модификации. Но если прям хочешь по красоте и по тестируемости, то нужно JSON было выбрать. (хотя уже поздно менять, но стоит балансировать между простотой и эффективностью)
А так все равно выглядит как overkill для проекта *такого масштаба*. Так просто набросал в csv строки данных, и пусть сам клиент разбирается с входными данными.

**Comment by rad55RUS** [comment]
Мы данные с каждого варика запихнули в один файл, т.к. они все привязаны к годам, поэтому разметка и пригодилась, особенно учитывая, что нам попался варик с субъектами, а их так дохера, поэтому мы просто взяли округи. Насчёт JSON согласен.

А так, я еще сам хотел поработать с БД в разметочном файле, а XML - первое, что пришло в голову)
